version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      cloudflare-tooling:
        patterns:
          - wrangler
          - "@cloudflare/*"
      tiptap-editor:
        patterns:
          - "@tiptap/*"
          - tiptap-markdown

  - package-ecosystem: github-actions
    directory: "/.github/workflows"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
